# Generated by Django 5.2.1 on 2025-06-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypingWord',
        ),
    ]
