# Generated by Django 5.2.1 on 2026-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
