# Generated by Django 5.2.1 on 2026-01-11 14:38

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_project_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='cv/'),
        ),
    ]
